version: "3.8"

# Diese Datei dient nur zum Starten von Admin-Tools für die Datenbank
# Kann parallel zu anderen Docker-Compose-Konfigurationen verwendet werden

services:
  adminer:
    image: adminer
    ports:
      - "8081:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=localhost
    restart: unless-stopped
    network_mode: host
      
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8082:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    restart: unless-stopped
    network_mode: host

volumes:
  pgadmin_data:
    driver: local
