spring:
  application:
    name: sportverein-backend
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/sportverein}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:none} # Schema-Verwaltung komplett an Flyway delegieren
    show-sql: ${SPRING_JPA_SHOW_SQL:true}
    properties:
      hibernate:
        "[format_sql]": true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    baseline-version: 0
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

# Server-Konfiguration
server:
  port: 8080
  servlet:
    context-path: /
  compression:
    enabled: true
